"""wix connection and website traffic tables

Revision ID: 05bf56b22ff4
Revises: 831378bc8449
Create Date: 2026-07-16 03:11:38.195230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '05bf56b22ff4'
down_revision: Union[str, None] = '831378bc8449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wix_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('site_display_name', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('website_daily_traffic',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_path', sa.String(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('visitors', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['wix_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'date', 'page_path', name='uq_traffic_connection_date_page')
    )
    op.create_index(op.f('ix_website_daily_traffic_date'), 'website_daily_traffic', ['date'], unique=False)
    op.create_table('website_form_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('form_name', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['wix_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_form_submissions_submitted_at'), 'website_form_submissions', ['submitted_at'], unique=False)
    op.create_table('wix_sync_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['wix_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_website_sessions_date', table_name='website_sessions')
    op.drop_table('website_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('medium', sa.VARCHAR(), nullable=True),
    sa.Column('campaign', sa.VARCHAR(), nullable=True),
    sa.Column('landing_page', sa.VARCHAR(), nullable=True),
    sa.Column('sessions', sa.INTEGER(), nullable=True),
    sa.Column('conversions', sa.INTEGER(), nullable=True),
    sa.Column('linked_post_id', sa.VARCHAR(), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['linked_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_website_sessions_date', 'website_sessions', ['date'], unique=False)
    op.drop_table('wix_sync_runs')
    op.drop_index(op.f('ix_website_form_submissions_submitted_at'), table_name='website_form_submissions')
    op.drop_table('website_form_submissions')
    op.drop_index(op.f('ix_website_daily_traffic_date'), table_name='website_daily_traffic')
    op.drop_table('website_daily_traffic')
    op.drop_table('wix_connections')
    # ### end Alembic commands ###
