"""manual metric overrides for reels

Revision ID: 1183dec891b9
Revises: 05bf56b22ff4
Create Date: 2026-07-16 15:57:10.443546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1183dec891b9'
down_revision: Union[str, None] = '05bf56b22ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('manual_profile_visits', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('manual_bio_link_taps', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('manual_follows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'manual_follows')
    op.drop_column('posts', 'manual_bio_link_taps')
    op.drop_column('posts', 'manual_profile_visits')
    # ### end Alembic commands ###
